vamp:
  environment:
    VAMP_DB_URL: http://elasticsearch:9200
  external_links:
  - ${zk_link}:zookeeper
  - ${elasticsearch_link}:elasticsearch
  tty: true
  image: rawmind/rancher-vamp:0.8.4
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
vamp-ui:
  external_links:
  - vamp:vamp
  tty: true
  image: rawmind/rancher-vamp-ui:0.8.4
