.catalog:
  name: Mongodb
  version: 0.0.1-rancher1
  description: |
    (Experimental) Mongodb replicaset.
  minimum_rancher_version: v0.47.0
  uuid: mongodb-0
  questions:
    - variable: "repset_name"
      description: "Name of the replicaset."
      label: "Repset Name:"
      required: true
      default: rs0
      type: "string"
    - variable: "repset_scale"
      description: "Number of repset nodes. Note: Recommended an odd number"
      label: "Repset Nodes:"
      required: true
      default: 3
      type: "int"
manager:
  scale: 1
repset:
  scale: ${repset_scale}
  health_check:
    port: 27017
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
